import { getAllOrgsWithStats, computeStats, getUpsellTargets } from "@/lib/superadmin-data";
import type { OrgWithStats } from "@/lib/superadmin-data";
import { StatsBar } from "@/components/superadmin/stats-bar";
import { SignupsTable } from "@/components/superadmin/signups-table";
import { UpsellTargetsTable } from "@/components/superadmin/upsell-targets-table";
import { CustomPlansTable } from "@/components/superadmin/custom-plans-table";
import { listCustomPlanRequests } from "@/actions/superadmin-custom-plan";
import { listPosts } from "@/actions/social";
import { countFeedback } from "@/actions/feedback";
import Link from "next/link";

export const dynamic = "force-dynamic";
export const metadata = { title: "JambaHR Admin — Dashboard" };

function LogoutButton() {
  return (
    <form action="/api/superadmin/logout" method="POST">
      <button
        type="submit"
        className="text-sm text-gray-500 hover:text-gray-700 underline"
      >
        Sign out
      </button>
    </form>
  );
}

export default async function SuperadminDashboard() {
  let orgs: OrgWithStats[] = [];
  try {
    orgs = await getAllOrgsWithStats();
  } catch {
    return (
      <div className="flex min-h-screen items-center justify-center text-red-600">
        Failed to load data. Check SUPABASE_SERVICE_ROLE_KEY and try again.
      </div>
    );
  }

  const stats = computeStats(orgs);
  const upsellTargets = getUpsellTargets(orgs);
  const customResult = await listCustomPlanRequests();
  const customRequests = customResult.success ? customResult.data : [];

  const [pendingResult, scheduledResult] = await Promise.all([
    listPosts("pending"),
    listPosts("scheduled"),
  ]);
  const socialCounts = {
    pending: pendingResult.success ? pendingResult.data.length : 0,
    scheduled: scheduledResult.success ? scheduledResult.data.length : 0,
  };

  const [feedbackNewResult, feedbackTriagedResult] = await Promise.all([
    countFeedback({ status: "new" }),
    countFeedback({ status: "triaged" }),
  ]);
  const feedbackCounts = {
    new: feedbackNewResult.success ? feedbackNewResult.data : 0,
    triaged: feedbackTriagedResult.success ? feedbackTriagedResult.data : 0,
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b border-gray-200 bg-white px-6 py-4">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-lg font-semibold text-gray-900">JambaHR Admin</h1>
            <p className="text-sm text-gray-500">Internal analytics — not customer-facing</p>
          </div>
          <LogoutButton />
        </div>
      </header>

      <main className="mx-auto max-w-7xl space-y-10 px-6 py-8">
        {/* Stats */}
        <section>
          <h2 className="mb-4 text-sm font-semibold uppercase tracking-wide text-gray-500">
            Overview
          </h2>
          <StatsBar stats={stats} />
        </section>

        {/* Social agent */}
        <section>
          <h2 className="mb-1 text-base font-semibold text-gray-900">Social Agent</h2>
          <p className="mb-4 text-sm text-gray-500">
            LinkedIn drafts generated by Claude, queued for your approval.
          </p>
          <Link
            href="/superadmin/social"
            className="flex items-center justify-between rounded-lg border border-gray-200 bg-white px-5 py-4 shadow-sm transition hover:border-gray-300 hover:shadow"
          >
            <div className="flex gap-6">
              <div>
                <p className="text-xs uppercase tracking-wide text-gray-500">Pending review</p>
                <p className="mt-1 text-2xl font-semibold text-gray-900">{socialCounts.pending}</p>
              </div>
              <div>
                <p className="text-xs uppercase tracking-wide text-gray-500">Scheduled</p>
                <p className="mt-1 text-2xl font-semibold text-gray-900">{socialCounts.scheduled}</p>
              </div>
            </div>
            <span className="text-sm text-teal-700">Open queue →</span>
          </Link>
        </section>

        {/* Feedback */}
        <section>
          <h2 className="mb-1 text-base font-semibold text-gray-900">Feedback</h2>
          <p className="mb-4 text-sm text-gray-500">
            Bug reports, feature requests, and freeform feedback from any role across all orgs.
          </p>
          <Link
            href="/superadmin/feedback"
            className="flex items-center justify-between rounded-lg border border-gray-200 bg-white px-5 py-4 shadow-sm transition hover:border-gray-300 hover:shadow"
          >
            <div className="flex gap-6">
              <div>
                <p className="text-xs uppercase tracking-wide text-gray-500">New</p>
                <p className="mt-1 text-2xl font-semibold text-gray-900">{feedbackCounts.new}</p>
              </div>
              <div>
                <p className="text-xs uppercase tracking-wide text-gray-500">Triaged</p>
                <p className="mt-1 text-2xl font-semibold text-gray-900">{feedbackCounts.triaged}</p>
              </div>
            </div>
            <span className="text-sm text-teal-700">Open inbox →</span>
          </Link>
        </section>

        {/* AI Assistant */}
        <section>
          <h2 className="mb-1 text-base font-semibold text-gray-900">AI Assistant</h2>
          <p className="mb-4 text-sm text-gray-500">
            Usage and cost analytics across all orgs. Aggregates only — no conversation content.
          </p>
          <Link
            href="/superadmin/assistant"
            className="flex items-center justify-between rounded-lg border border-gray-200 bg-white px-5 py-4 shadow-sm transition hover:border-gray-300 hover:shadow"
          >
            <div className="flex gap-6">
              <div>
                <p className="text-xs uppercase tracking-wide text-gray-500">Messages (30d)</p>
                <p className="mt-1 text-2xl font-semibold text-gray-900">—</p>
              </div>
              <div>
                <p className="text-xs uppercase tracking-wide text-gray-500">Est. cost (30d)</p>
                <p className="mt-1 text-2xl font-semibold text-gray-900">—</p>
              </div>
            </div>
            <span className="text-sm text-teal-700">View analytics →</span>
          </Link>
        </section>

        {/* Operations Runbooks */}
        <section>
          <h2 className="mb-1 text-base font-semibold text-gray-900">Runbooks</h2>
          <p className="mb-4 text-sm text-gray-500">
            Internal setup &amp; troubleshooting guides (biometric relay, etc.). Founder-only.
          </p>
          <Link
            href="/superadmin/runbooks"
            className="flex items-center justify-between rounded-lg border border-gray-200 bg-white px-5 py-4 shadow-sm transition hover:border-gray-300 hover:shadow"
          >
            <div>
              <p className="text-sm font-medium text-gray-900">Operations Runbooks</p>
              <p className="mt-1 text-sm text-gray-500">Step-by-step ops guides</p>
            </div>
            <span className="text-sm text-teal-700">Open →</span>
          </Link>
          <Link
            href="/superadmin/groups"
            className="mt-3 flex items-center justify-between rounded-lg border border-gray-200 bg-white px-5 py-4 shadow-sm transition hover:border-gray-300 hover:shadow"
          >
            <div>
              <p className="text-sm font-medium text-gray-900">Company Groups</p>
              <p className="mt-1 text-sm text-gray-500">Link orgs for cross-org attendance (e.g. TMP)</p>
            </div>
            <span className="text-sm text-teal-700">Open →</span>
          </Link>
        </section>

        {/* Custom plan requests */}
        <section>
          <h2 className="mb-1 text-base font-semibold text-gray-900">
            Custom Plan Queue
          </h2>
          <p className="mb-4 text-sm text-gray-500">
            Active requests awaiting founder review. {customRequests.length} pending.
          </p>
          <CustomPlansTable requests={customRequests} />
        </section>

        {/* Upsell targets */}
        <section>
          <h2 className="mb-1 text-base font-semibold text-gray-900">
            Upsell Targets
          </h2>
          <p className="mb-4 text-sm text-gray-500">
            Starter orgs with ≥7 employees (near limit) or ≥3 employees and 30+ days old (engaged, not converted).
          </p>
          <UpsellTargetsTable targets={upsellTargets} />
        </section>

        {/* All signups */}
        <section>
          <h2 className="mb-1 text-base font-semibold text-gray-900">
            All Signups
          </h2>
          <p className="mb-4 text-sm text-gray-500">
            {orgs.length} total org{orgs.length !== 1 ? "s" : ""} — newest first.
          </p>
          <SignupsTable orgs={orgs} />
        </section>
      </main>
    </div>
  );
}
