// Inputs and expected outputs read cell-by-cell from Medialoop's two salary
// workbooks (docs/planning/payroll/, never committed): the OLD-EPF sheet
// ("Salary Format _ver0.00b _ CTC", titled July 2026) and the NEW-EPF sheet
// ("Salary Sheet Format _NNver0.00a", titled Oct 2026). Generated by a script
// from the cached cell values; `fixed` holds the per-row constants hard-coded
// inside each allowance formula (e.g. =(25000/$F$4*P9)).
//
// Employee codes only — names, UAN and ESIC numbers are deliberately left out.
// The sheets do not round, so expected values carry paise (e.g. ESI 131.25).

export type SheetRow = {
  code: string;
  gender: "M" | "F";
  gross: number;
  weeklyOff: number;
  holidays: number;
  lateJoinDays: number;
  daysPaid: number;
  fixed: Record<string, number>;
  expected: Record<string, number | boolean>;
};

export type SheetFixture = { daysInMonth: number; rows: SheetRow[] };

export const OLD_EPF_SHEET: SheetFixture = {
  "daysInMonth": 31,
  "rows": [
    {
      "code": "001",
      "gender": "F",
      "gross": 225000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 25000,
        "LTA": 10000,
        "COMMISSION": 21250
      },
      "expected": {
        "BASIC": 112500,
        "HRA": 56250,
        "CONV": 25000,
        "LTA": 10000,
        "COMMISSION": 21250,
        "SPECIAL": 0,
        "gross": 225000,
        "EPF_EE": 1800,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2000,
        "net": 223000,
        "EPF_ER": 1800,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 1800,
        "ctc": 226800
      }
    },
    {
      "code": "002",
      "gender": "F",
      "gross": 100000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 15000,
        "LTA": 7500,
        "COMMISSION": 2500
      },
      "expected": {
        "BASIC": 50000,
        "HRA": 25000,
        "CONV": 15000,
        "LTA": 7500,
        "COMMISSION": 2500,
        "SPECIAL": 0,
        "gross": 100000,
        "EPF_EE": 1800,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2000,
        "net": 98000,
        "EPF_ER": 1800,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 1800,
        "ctc": 101800
      }
    },
    {
      "code": "003",
      "gender": "M",
      "gross": 65000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 7500,
        "LTA": 5000,
        "COMMISSION": 3750
      },
      "expected": {
        "BASIC": 32500,
        "HRA": 16250,
        "CONV": 7500,
        "LTA": 5000,
        "COMMISSION": 3750,
        "SPECIAL": 0,
        "gross": 65000,
        "EPF_EE": 1800,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2000,
        "net": 63000,
        "EPF_ER": 1800,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 1800,
        "ctc": 66800
      }
    },
    {
      "code": "004",
      "gender": "F",
      "gross": 65000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 7500,
        "LTA": 5000,
        "COMMISSION": 3750
      },
      "expected": {
        "BASIC": 32500,
        "HRA": 16250,
        "CONV": 7500,
        "LTA": 5000,
        "COMMISSION": 3750,
        "SPECIAL": 0,
        "gross": 65000,
        "EPF_EE": 1800,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2000,
        "net": 63000,
        "EPF_ER": 1800,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 1800,
        "ctc": 66800
      }
    },
    {
      "code": "005",
      "gender": "M",
      "gross": 45000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 5000,
        "LTA": 5000,
        "COMMISSION": 1250
      },
      "expected": {
        "BASIC": 22500,
        "HRA": 11250,
        "CONV": 5000,
        "LTA": 5000,
        "COMMISSION": 1250,
        "SPECIAL": 0,
        "gross": 45000,
        "EPF_EE": 1800,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2000,
        "net": 43000,
        "EPF_ER": 1800,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 1800,
        "ctc": 46800
      }
    },
    {
      "code": "006",
      "gender": "M",
      "gross": 35000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 5750,
        "LTA": 3000,
        "COMMISSION": 0
      },
      "expected": {
        "BASIC": 17500,
        "HRA": 8750,
        "CONV": 5750,
        "LTA": 3000,
        "COMMISSION": 0,
        "SPECIAL": 0,
        "gross": 35000,
        "EPF_EE": 1800,
        "ESI_EE": 131.25,
        "esiApplicable": true,
        "PT": 200,
        "totalDeductions": 2131.25,
        "net": 32868.75,
        "EPF_ER": 1800,
        "ESI_ER": 568.75,
        "LWF_ER": 0,
        "employerTotal": 2368.75,
        "ctc": 37368.75
      }
    },
    {
      "code": "007",
      "gender": "M",
      "gross": 65000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 7500,
        "LTA": 5000,
        "COMMISSION": 3750
      },
      "expected": {
        "BASIC": 32500,
        "HRA": 16250,
        "CONV": 7500,
        "LTA": 5000,
        "COMMISSION": 3750,
        "SPECIAL": 0,
        "gross": 65000,
        "EPF_EE": 1800,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2000,
        "net": 63000,
        "EPF_ER": 1800,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 1800,
        "ctc": 66800
      }
    },
    {
      "code": "008",
      "gender": "M",
      "gross": 50000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 7500,
        "LTA": 5000,
        "COMMISSION": 0
      },
      "expected": {
        "BASIC": 25000,
        "HRA": 12500,
        "CONV": 7500,
        "LTA": 5000,
        "COMMISSION": 0,
        "SPECIAL": 0,
        "gross": 50000,
        "EPF_EE": 1800,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2000,
        "net": 48000,
        "EPF_ER": 1800,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 1800,
        "ctc": 51800
      }
    },
    {
      "code": "009",
      "gender": "F",
      "gross": 35000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 5000,
        "LTA": 3750,
        "COMMISSION": 0
      },
      "expected": {
        "BASIC": 17500,
        "HRA": 8750,
        "CONV": 5000,
        "LTA": 3750,
        "COMMISSION": 0,
        "SPECIAL": 0,
        "gross": 35000,
        "EPF_EE": 1800,
        "ESI_EE": 131.25,
        "esiApplicable": true,
        "PT": 200,
        "totalDeductions": 2131.25,
        "net": 32868.75,
        "EPF_ER": 1800,
        "ESI_ER": 568.75,
        "LWF_ER": 0,
        "employerTotal": 2368.75,
        "ctc": 37368.75
      }
    },
    {
      "code": "010",
      "gender": "M",
      "gross": 62000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 7500,
        "LTA": 5000,
        "COMMISSION": 3000
      },
      "expected": {
        "BASIC": 31000,
        "HRA": 15500,
        "CONV": 7500,
        "LTA": 5000,
        "COMMISSION": 3000,
        "SPECIAL": 0,
        "gross": 62000,
        "EPF_EE": 1800,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2000,
        "net": 60000,
        "EPF_ER": 1800,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 1800,
        "ctc": 63800
      }
    },
    {
      "code": "011",
      "gender": "M",
      "gross": 50000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 5000,
        "LTA": 5000,
        "COMMISSION": 2500
      },
      "expected": {
        "BASIC": 25000,
        "HRA": 12500,
        "CONV": 5000,
        "LTA": 5000,
        "COMMISSION": 2500,
        "SPECIAL": 0,
        "gross": 50000,
        "EPF_EE": 1800,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2000,
        "net": 48000,
        "EPF_ER": 1800,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 1800,
        "ctc": 51800
      }
    },
    {
      "code": "012",
      "gender": "M",
      "gross": 20000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 5000,
        "LTA": 0,
        "COMMISSION": 0
      },
      "expected": {
        "BASIC": 10000,
        "HRA": 5000,
        "CONV": 5000,
        "LTA": 0,
        "COMMISSION": 0,
        "SPECIAL": 0,
        "gross": 20000,
        "EPF_EE": 1200,
        "ESI_EE": 75,
        "esiApplicable": true,
        "PT": 200,
        "totalDeductions": 1475,
        "net": 18525,
        "EPF_ER": 1200,
        "ESI_ER": 325,
        "LWF_ER": 0,
        "employerTotal": 1525,
        "ctc": 21525
      }
    },
    {
      "code": "013",
      "gender": "M",
      "gross": 20000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 5000,
        "LTA": 0,
        "COMMISSION": 0
      },
      "expected": {
        "BASIC": 10000,
        "HRA": 5000,
        "CONV": 5000,
        "LTA": 0,
        "COMMISSION": 0,
        "SPECIAL": 0,
        "gross": 20000,
        "EPF_EE": 1200,
        "ESI_EE": 75,
        "esiApplicable": true,
        "PT": 200,
        "totalDeductions": 1475,
        "net": 18525,
        "EPF_ER": 1200,
        "ESI_ER": 325,
        "LWF_ER": 0,
        "employerTotal": 1525,
        "ctc": 21525
      }
    },
    {
      "code": "014",
      "gender": "F",
      "gross": 20000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 5000,
        "LTA": 0,
        "COMMISSION": 0
      },
      "expected": {
        "BASIC": 10000,
        "HRA": 5000,
        "CONV": 5000,
        "LTA": 0,
        "COMMISSION": 0,
        "SPECIAL": 0,
        "gross": 20000,
        "EPF_EE": 1200,
        "ESI_EE": 75,
        "esiApplicable": true,
        "PT": 0,
        "totalDeductions": 1275,
        "net": 18725,
        "EPF_ER": 1200,
        "ESI_ER": 325,
        "LWF_ER": 0,
        "employerTotal": 1525,
        "ctc": 21525
      }
    },
    {
      "code": "015",
      "gender": "F",
      "gross": 25000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 5000,
        "LTA": 1250,
        "COMMISSION": 0
      },
      "expected": {
        "BASIC": 12500,
        "HRA": 6250,
        "CONV": 5000,
        "LTA": 1250,
        "COMMISSION": 0,
        "SPECIAL": 0,
        "gross": 25000,
        "EPF_EE": 1500,
        "ESI_EE": 93.75,
        "esiApplicable": true,
        "PT": 0,
        "totalDeductions": 1593.75,
        "net": 23406.25,
        "EPF_ER": 1500,
        "ESI_ER": 406.25,
        "LWF_ER": 0,
        "employerTotal": 1906.25,
        "ctc": 26906.25
      }
    },
    {
      "code": "016",
      "gender": "F",
      "gross": 30000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 5000,
        "LTA": 2500,
        "COMMISSION": 0
      },
      "expected": {
        "BASIC": 15000,
        "HRA": 7500,
        "CONV": 5000,
        "LTA": 2500,
        "COMMISSION": 0,
        "SPECIAL": 0,
        "gross": 30000,
        "EPF_EE": 1800,
        "ESI_EE": 112.5,
        "esiApplicable": true,
        "PT": 200,
        "totalDeductions": 2112.5,
        "net": 27887.5,
        "EPF_ER": 1800,
        "ESI_ER": 487.5,
        "LWF_ER": 0,
        "employerTotal": 2287.5,
        "ctc": 32287.5
      }
    },
    {
      "code": "017",
      "gender": "F",
      "gross": 80000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "CONV": 10000,
        "LTA": 7500,
        "COMMISSION": 2500
      },
      "expected": {
        "BASIC": 40000,
        "HRA": 20000,
        "CONV": 10000,
        "LTA": 7500,
        "COMMISSION": 2500,
        "SPECIAL": 0,
        "gross": 80000,
        "EPF_EE": 1800,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2000,
        "net": 78000,
        "EPF_ER": 1800,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 1800,
        "ctc": 81800
      }
    }
  ]
};

export const NEW_EPF_SHEET: SheetFixture = {
  "daysInMonth": 31,
  "rows": [
    {
      "code": "001",
      "gender": "F",
      "gross": 225000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 15000,
        "CONV": 25000
      },
      "expected": {
        "BASIC": 112500,
        "HRA": 45000,
        "LTA": 15000,
        "CONV": 25000,
        "SPECIAL": 27500,
        "gross": 225000,
        "EPF_EE": 3000,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 3200,
        "net": 221800,
        "EPF_ER": 3000,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 3000,
        "ctc": 228000
      }
    },
    {
      "code": "002",
      "gender": "F",
      "gross": 100000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 10000,
        "CONV": 20000
      },
      "expected": {
        "BASIC": 50000,
        "HRA": 20000,
        "LTA": 10000,
        "CONV": 20000,
        "SPECIAL": 0,
        "gross": 100000,
        "EPF_EE": 3000,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 3200,
        "net": 96800,
        "EPF_ER": 3000,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 3000,
        "ctc": 103000
      }
    },
    {
      "code": "003",
      "gender": "M",
      "gross": 65000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 6500,
        "CONV": 13000
      },
      "expected": {
        "BASIC": 32500.000000000004,
        "HRA": 13000.000000000002,
        "LTA": 6500,
        "CONV": 13000,
        "SPECIAL": 0,
        "gross": 65000.00000000001,
        "EPF_EE": 3000,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 3200,
        "net": 61800.00000000001,
        "EPF_ER": 3000,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 3000,
        "ctc": 68000
      }
    },
    {
      "code": "004",
      "gender": "F",
      "gross": 65000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 6500,
        "CONV": 13000
      },
      "expected": {
        "BASIC": 32500.000000000004,
        "HRA": 13000.000000000002,
        "LTA": 6500,
        "CONV": 13000,
        "SPECIAL": 0,
        "gross": 65000.00000000001,
        "EPF_EE": 3000,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 3200,
        "net": 61800.00000000001,
        "EPF_ER": 3000,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 3000,
        "ctc": 68000
      }
    },
    {
      "code": "005",
      "gender": "M",
      "gross": 45000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 3500,
        "CONV": 10000
      },
      "expected": {
        "BASIC": 22500,
        "HRA": 9000,
        "LTA": 3500,
        "CONV": 10000,
        "SPECIAL": 0,
        "gross": 45000,
        "EPF_EE": 2700,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 2900,
        "net": 42100,
        "EPF_ER": 2700,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 2700,
        "ctc": 47700
      }
    },
    {
      "code": "006",
      "gender": "M",
      "gross": 35000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 3000,
        "CONV": 7500
      },
      "expected": {
        "BASIC": 17500,
        "HRA": 7000,
        "LTA": 3000,
        "CONV": 7500,
        "SPECIAL": 0,
        "gross": 35000,
        "EPF_EE": 2100,
        "ESI_EE": 131.25,
        "esiApplicable": true,
        "PT": 200,
        "totalDeductions": 2431.25,
        "net": 32568.75,
        "EPF_ER": 2100,
        "ESI_ER": 568.75,
        "LWF_ER": 0,
        "employerTotal": 2668.75,
        "ctc": 37668.75
      }
    },
    {
      "code": "007",
      "gender": "M",
      "gross": 65000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 6500,
        "CONV": 13000
      },
      "expected": {
        "BASIC": 32500.000000000004,
        "HRA": 13000.000000000002,
        "LTA": 6500,
        "CONV": 13000,
        "SPECIAL": 0,
        "gross": 65000.00000000001,
        "EPF_EE": 3000,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 3200,
        "net": 61800.00000000001,
        "EPF_ER": 3000,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 3000,
        "ctc": 68000
      }
    },
    {
      "code": "008",
      "gender": "M",
      "gross": 50000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 5000,
        "CONV": 10000
      },
      "expected": {
        "BASIC": 25000,
        "HRA": 10000,
        "LTA": 5000,
        "CONV": 10000,
        "SPECIAL": 0,
        "gross": 50000,
        "EPF_EE": 3000,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 3200,
        "net": 46800,
        "EPF_ER": 3000,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 3000,
        "ctc": 53000
      }
    },
    {
      "code": "009",
      "gender": "F",
      "gross": 35000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 3000,
        "CONV": 7500
      },
      "expected": {
        "BASIC": 17500,
        "HRA": 7000,
        "LTA": 3000,
        "CONV": 7500,
        "SPECIAL": 0,
        "gross": 35000,
        "EPF_EE": 2100,
        "ESI_EE": 131.25,
        "esiApplicable": true,
        "PT": 200,
        "totalDeductions": 2431.25,
        "net": 32568.75,
        "EPF_ER": 2100,
        "ESI_ER": 568.75,
        "LWF_ER": 0,
        "employerTotal": 2668.75,
        "ctc": 37668.75
      }
    },
    {
      "code": "010",
      "gender": "M",
      "gross": 62000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 5600,
        "CONV": 13000
      },
      "expected": {
        "BASIC": 31000,
        "HRA": 12400,
        "LTA": 5600,
        "CONV": 13000,
        "SPECIAL": 0,
        "gross": 62000,
        "EPF_EE": 3000,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 3200,
        "net": 58800,
        "EPF_ER": 3000,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 3000,
        "ctc": 65000
      }
    },
    {
      "code": "011",
      "gender": "M",
      "gross": 50000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 5000,
        "CONV": 10000
      },
      "expected": {
        "BASIC": 25000,
        "HRA": 10000,
        "LTA": 5000,
        "CONV": 10000,
        "SPECIAL": 0,
        "gross": 50000,
        "EPF_EE": 3000,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 3200,
        "net": 46800,
        "EPF_ER": 3000,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 3000,
        "ctc": 53000
      }
    },
    {
      "code": "012",
      "gender": "M",
      "gross": 20000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 0,
        "CONV": 6000
      },
      "expected": {
        "BASIC": 10000,
        "HRA": 4000,
        "LTA": 0,
        "CONV": 6000,
        "SPECIAL": 0,
        "gross": 20000,
        "EPF_EE": 1200,
        "ESI_EE": 75,
        "esiApplicable": true,
        "PT": 200,
        "totalDeductions": 1475,
        "net": 18525,
        "EPF_ER": 1200,
        "ESI_ER": 325,
        "LWF_ER": 0,
        "employerTotal": 1525,
        "ctc": 21525
      }
    },
    {
      "code": "013",
      "gender": "M",
      "gross": 20000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 0,
        "CONV": 6000
      },
      "expected": {
        "BASIC": 10000,
        "HRA": 4000,
        "LTA": 0,
        "CONV": 6000,
        "SPECIAL": 0,
        "gross": 20000,
        "EPF_EE": 1200,
        "ESI_EE": 75,
        "esiApplicable": true,
        "PT": 200,
        "totalDeductions": 1475,
        "net": 18525,
        "EPF_ER": 1200,
        "ESI_ER": 325,
        "LWF_ER": 0,
        "employerTotal": 1525,
        "ctc": 21525
      }
    },
    {
      "code": "014",
      "gender": "F",
      "gross": 20000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 0,
        "CONV": 6000
      },
      "expected": {
        "BASIC": 10000,
        "HRA": 4000,
        "LTA": 0,
        "CONV": 6000,
        "SPECIAL": 0,
        "gross": 20000,
        "EPF_EE": 1200,
        "ESI_EE": 75,
        "esiApplicable": true,
        "PT": 0,
        "totalDeductions": 1275,
        "net": 18725,
        "EPF_ER": 1200,
        "ESI_ER": 325,
        "LWF_ER": 0,
        "employerTotal": 1525,
        "ctc": 21525
      }
    },
    {
      "code": "015",
      "gender": "F",
      "gross": 25000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 0,
        "CONV": 7500
      },
      "expected": {
        "BASIC": 12500,
        "HRA": 5000,
        "LTA": 0,
        "CONV": 7500,
        "SPECIAL": 0,
        "gross": 25000,
        "EPF_EE": 1500,
        "ESI_EE": 93.75,
        "esiApplicable": true,
        "PT": 0,
        "totalDeductions": 1593.75,
        "net": 23406.25,
        "EPF_ER": 1500,
        "ESI_ER": 406.25,
        "LWF_ER": 0,
        "employerTotal": 1906.25,
        "ctc": 26906.25
      }
    },
    {
      "code": "016",
      "gender": "F",
      "gross": 30000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 2500,
        "CONV": 6500
      },
      "expected": {
        "BASIC": 15000,
        "HRA": 6000,
        "LTA": 2500,
        "CONV": 6500,
        "SPECIAL": 0,
        "gross": 30000,
        "EPF_EE": 1800,
        "ESI_EE": 112.5,
        "esiApplicable": true,
        "PT": 200,
        "totalDeductions": 2112.5,
        "net": 27887.5,
        "EPF_ER": 1800,
        "ESI_ER": 487.5,
        "LWF_ER": 0,
        "employerTotal": 2287.5,
        "ctc": 32287.5
      }
    },
    {
      "code": "017",
      "gender": "F",
      "gross": 80000,
      "weeklyOff": 4,
      "holidays": 0,
      "lateJoinDays": 0,
      "daysPaid": 31,
      "fixed": {
        "LTA": 9000,
        "CONV": 15000
      },
      "expected": {
        "BASIC": 40000,
        "HRA": 16000,
        "LTA": 9000,
        "CONV": 15000,
        "SPECIAL": 0,
        "gross": 80000,
        "EPF_EE": 3000,
        "ESI_EE": 0,
        "esiApplicable": false,
        "PT": 200,
        "totalDeductions": 3200,
        "net": 76800,
        "EPF_ER": 3000,
        "ESI_ER": 0,
        "LWF_ER": 0,
        "employerTotal": 3000,
        "ctc": 83000
      }
    }
  ]
};
