import Link from "next/link";
import { listPosts } from "@/actions/social";
import { PostPreviewCard } from "@/components/superadmin/social/post-preview-card";
import type { SocialPost } from "@/lib/social/types";

export const dynamic = "force-dynamic";
export const metadata = { title: "JambaHR Admin — Social Agent" };

type Tab = "pending" | "scheduled" | "history";
const TABS: { key: Tab; label: string; filter: "pending" | "scheduled" | "all" }[] = [
  { key: "pending", label: "Pending review", filter: "pending" },
  { key: "scheduled", label: "Scheduled", filter: "scheduled" },
  { key: "history", label: "History", filter: "all" },
];

export default async function SuperadminSocialPage({
  searchParams,
}: {
  searchParams: { tab?: string };
}) {
  const activeTab: Tab =
    searchParams.tab === "scheduled" || searchParams.tab === "history"
      ? searchParams.tab
      : "pending";

  const tab = TABS.find((t) => t.key === activeTab)!;
  const result = await listPosts(tab.filter);
  let posts: SocialPost[] = [];
  let errorMsg: string | null = null;

  if (result.success) {
    posts = activeTab === "history"
      ? result.data.filter((p) => p.status === "published" || p.status === "failed" || p.status === "rejected")
      : result.data;
  } else {
    errorMsg = result.error;
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b border-gray-200 bg-white px-6 py-4">
        <div className="flex items-center justify-between">
          <div>
            <Link href="/superadmin/dashboard" className="text-xs text-gray-500 hover:underline">
              ← Back to admin dashboard
            </Link>
            <h1 className="mt-1 text-lg font-semibold text-gray-900">Social Agent</h1>
            <p className="text-sm text-gray-500">
              JambaHR LinkedIn page · drafts generated by Claude, posted via Buffer
            </p>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-8">
        <div className="mb-6 flex gap-2 border-b border-gray-200">
          {TABS.map((t) => {
            const active = t.key === activeTab;
            return (
              <Link
                key={t.key}
                href={`/superadmin/social?tab=${t.key}`}
                className={
                  active
                    ? "border-b-2 border-teal-600 px-4 py-2 text-sm font-semibold text-teal-700"
                    : "border-b-2 border-transparent px-4 py-2 text-sm text-gray-500 hover:text-gray-800"
                }
              >
                {t.label}
              </Link>
            );
          })}
        </div>

        {errorMsg ? (
          <div className="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            {errorMsg}
          </div>
        ) : posts.length === 0 ? (
          <EmptyState tab={activeTab} />
        ) : (
          <div className="space-y-3">
            {posts.map((p) => (
              <PostPreviewCard key={p.id} post={p} />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}

function EmptyState({ tab }: { tab: Tab }) {
  const messages: Record<Tab, string> = {
    pending: "No drafts waiting for review. The agent generates new ones on Mon/Wed/Fri at 9:30 IST.",
    scheduled: "Nothing scheduled. Approve a pending draft to push it to Buffer's queue.",
    history: "No published or rejected posts yet.",
  };
  return (
    <div className="rounded-lg border border-dashed border-gray-300 bg-white px-6 py-12 text-center text-sm text-gray-500">
      {messages[tab]}
    </div>
  );
}
